# Generated by Django 5.2.7 on 2026-04-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cash_received',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
