# Generated by Django 5.2.7 on 2026-04-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=150)),
                ('registration_number', models.CharField(max_length=50)),
                ('traveled_by', models.CharField(max_length=150)),
                ('purpose_of_trip', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('maintenance_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('odometer_start', models.DecimalField(blank=True, decimal_places=2, help_text='Odometer reading at trip start (km)', max_digits=10, null=True)),
                ('odometer_start_image', models.ImageField(blank=True, null=True, upload_to='trips/odometer/start/')),
                ('services', models.CharField(blank=True, default='', help_text="Comma-separated list of services performed (e.g. 'washing,alignment')", max_length=200)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('odometer_end', models.DecimalField(blank=True, decimal_places=2, help_text='Odometer reading at trip end (km)', max_digits=10, null=True)),
                ('distance_covered', models.DecimalField(blank=True, decimal_places=2, help_text='Computed: odometer_end - odometer_start (km)', max_digits=10, null=True)),
                ('fuel_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('odometer_end_image', models.ImageField(blank=True, null=True, upload_to='trips/odometer/end/')),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Travel Trip',
                'verbose_name_plural': 'Travel Trips',
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
