# Generated by Django 5.2.7 on 2026-04-07 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiclemaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Default / entry date')),
                ('challan_no', models.CharField(max_length=100, unique=True)),
                ('challan_date', models.DateField()),
                ('offence_type', models.CharField(choices=[('Signal Jumping', 'Signal Jumping'), ('Over Speeding', 'Over Speeding'), ('Drunk Driving', 'Drunk Driving'), ('Wrong Parking', 'Wrong Parking'), ('No Helmet', 'No Helmet'), ('No Seatbelt', 'No Seatbelt'), ('Using Mobile While Driving', 'Using Mobile While Driving'), ('Overloading', 'Overloading'), ('No License', 'No License'), ('No Insurance', 'No Insurance'), ('Triple Riding', 'Triple Riding'), ('Lane Violation', 'Lane Violation'), ('Other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Waived', 'Waived')], default='Pending', max_length=20)),
                ('challan_doc', models.FileField(blank=True, null=True, upload_to='challans/docs/')),
                ('payment_receipt', models.FileField(blank=True, null=True, upload_to='challans/receipts/')),
                ('remark', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challans', to='vehiclemaster.vehiclemaster')),
            ],
            options={
                'db_table': 'challan',
                'ordering': ['-created_at'],
            },
        ),
    ]
