# Generated by Django 5.2.7 on 2026-04-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=100)),
                ('company_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_type', models.CharField(blank=True, choices=[('Car', 'Car'), ('Bike', 'Bike'), ('Truck', 'Truck'), ('Bus', 'Bus'), ('Van', 'Van'), ('Other', 'Other')], max_length=20, null=True)),
                ('ownership', models.CharField(blank=True, choices=[('Personal', 'Personal'), ('Company', 'Company'), ('Leased', 'Leased'), ('Rental', 'Rental')], max_length=20, null=True)),
                ('fuel_type', models.CharField(blank=True, choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('CNG', 'CNG')], max_length=20, null=True)),
                ('vehicle_photo', models.ImageField(blank=True, null=True, upload_to='vehicles/photos/')),
                ('owner_name', models.CharField(max_length=150)),
                ('insurance_no', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_expired_date', models.DateField(blank=True, null=True)),
                ('pollution_expired_date', models.DateField(blank=True, null=True)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('current_odometer', models.PositiveIntegerField(default=0)),
                ('chassis_number', models.CharField(blank=True, max_length=100, null=True)),
                ('engine_number', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('total_trips', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle Master',
                'verbose_name_plural': 'Vehicle Masters',
                'db_table': 'vehicle_master',
                'ordering': ['-created_at'],
            },
        ),
    ]
