# Generated by Django 5.2.7 on 2026-04-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='expense_type',
            field=models.CharField(choices=[('self_expense', 'Self Expense'), ('travel_expense', 'Travel Expense'), ('food_expense', 'Food Expense'), ('accommodation', 'Accommodation Expense'), ('fuel', 'Fuel Expense'), ('parking', 'Parking Expense'), ('toll', 'Toll Expense')], max_length=30),
        ),
    ]
