# Generated by Django 5.2.7 on 2026-04-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_alter_claim_expense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='department',
            field=models.CharField(max_length=20),
        ),
    ]
