# Generated by Django 5.2.7 on 2026-03-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontrol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menupermission',
            name='user',
        ),
        migrations.AddField(
            model_name='menupermission',
            name='login_user_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]