# Generated by Django 5.2.7 on 2026-04-01 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercontrol', '0002_remove_menupermission_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
