# Generated by Django 5.2.7 on 2026-04-01 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontrol', '0003_remove_customuser_branch_remove_customuser_groups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menupermission',
            options={'verbose_name': 'Menu Permission', 'verbose_name_plural': 'Menu Permissions'},
        ),
        migrations.RemoveField(
            model_name='menupermission',
            name='login_user_id',
        ),
        migrations.AddField(
            model_name='menupermission',
            name='login_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_permissions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
