# Generated by Django 5.2.7 on 2026-04-01 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercontrol', '0004_alter_menupermission_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menupermission',
            table='usercontrol_menupermission',
        ),
    ]
