# Generated by Django 5.2.7 on 2026-04-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontrol', '0006_menupermission_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menupermission',
            name='mm_vehicle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menupermission',
            name='vm_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menupermission',
            name='vm_trips',
            field=models.BooleanField(default=False),
        ),
    ]
