# Generated by Django 5.2.7 on 2026-04-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontrol', '0007_menupermission_mm_vehicle_menupermission_vm_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menupermission',
            name='cl_list',
            field=models.BooleanField(default=False),
        ),
    ]
