# Generated by Django 5.2.7 on 2026-04-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontrol', '0008_menupermission_cl_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='menupermission',
            name='col_reports_view',
            field=models.BooleanField(default=False),
        ),
    ]
