# Generated by Django 5.2.7 on 2026-04-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontrol', '0009_menupermission_col_reports_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='menupermission',
            name='image_capture',
            field=models.BooleanField(default=False),
        ),
    ]
