# Generated by Django 5.2.7 on 2026-03-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_address_user_phone_user_status_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
