# Generated by Django 5.2.7 on 2026-04-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional profile photo (JPEG/PNG)', null=True, upload_to='user_photos/'),
        ),
    ]
