# Generated by Django 5.2.7 on 2026-04-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Super Admin', 'Super Admin'), ('User', 'User')], default='User', max_length=20),
        ),
    ]
