# Generated by Django 5.2.7 on 2026-04-02 05:40

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_options_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional profile photo (JPEG / PNG, max 5 MB)', null=True, upload_to=user.models.user_photo_upload_path),
        ),
    ]
