# Generated by Django 5.2.7 on 2026-04-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Operator', 'Operator'), ('user', 'user'), ('Support', 'Support'), ('Auditor', 'Auditor')], max_length=20),
        ),
    ]
